$schema: https://json-schema.org/draft/2020-12/schema
title: "Application extension"
description: "STAC Application Extension for Items, Collections and Catalogs."
allOf:
  - anyOf:
      - $ref: bblocks://ogc.contrib.stac.collection
      - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://stac-extensions.github.io/application/v0.1.0/schema.json
