$schema: https://json-schema.org/draft/2020-12/schema
title: "Versioning Indicators extension"
description: "STAC Versioning Indicators Extension for STAC resources and assets."
allOf:
  - anyOf:
      - $ref: bblocks://ogc.contrib.stac.collection
      - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://stac-extensions.github.io/version/v1.2.0/schema.json
