$schema: https://json-schema.org/draft/2020-12/schema
title: "Scientific Citation extension"
description: "STAC Scientific Citation Extension for Items and Collections."
allOf:
  - anyOf:
      - $ref: bblocks://ogc.contrib.stac.collection
      - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://stac-extensions.github.io/scientific/v1.0.0/schema.json
